# Generated by Django 5.1.7 on 2025-03-10 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rating_app", "0002_alter_customuser_groups_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rating",
            name="rating",
            field=models.IntegerField(),
        ),
    ]
